---
## This playbook deploys the whole application stack in this site.

# Apply common configuration to all hosts
- hosts: localhost
  connection: local
  become: no
  roles:
#  - monerole
#  - ansible-role-onion
  - tortestio
#  - outerrole #permissions issue when copying folder over.

- hosts: server
  roles:
  - serverlisten
  
- hosts: client
  roles:
  - tortestio
