---
## This playbook deploys the whole application stack in this site.

# Apply common configuration to all hosts
- hosts: localhost
  become: no
  roles:
#  - monerole
#  - ansible-role-onion
  - outerrole
