---
# tasks file for outerrole

#  - name: git clone chutney
#    ansible.builtin.git:
#      repo: https://github.com/torproject/chutney.git
#      dest: /home/vagrant/chutney
#      clone: yes
#      update: yes

  - name: Delete chutney in shared folder
    file:
      state: absent
      path: "/home/g/naanbread/chutneyforvagrant/sharedfolder/chutney/net/"

  - name: copy all chutneyfiles into shared folder
    copy:
      src: /home/g/naanbread/chutneygitrepo/ # note the '/' <-- !!!
      dest: /home/g/naanbread/chutneyforvagrant/sharedfolder/chutney/
      mode: preserve

#  - name: Replace line in hscommon for listeningport num in shared folder
#    lineinfile:
#      path: "/home/g/naanbread/chutneyforvagrant/sharedfolder/chutney/torrc_templates/hs-common.i"
#      search_string: 'HiddenServicePort'
#      line: "{{'HiddenServicePort ' + hsport + ' 127.0.0.1:' + hsport}}"


  - name: spin up vagrant
    ansible.builtin.shell: "vagrant up"
    args:
      chdir: /home/g/naanbread/chutneyforvagrant/

  - name: spin up server
    ansible.builtin.shell: "vagrant provision onionservice"
    args:
      chdir: /home/g/naanbread/chutneyforvagrant/

  - name: spin up client
    ansible.builtin.shell: "vagrant provision onionclient"
    args:
      chdir: /home/g/naanbread/chutneyforvagrant/


